### ISSUE TITLE
Cover image

### ISSUE THREAD

**Issue by diofanto33** [zhimin-z/zhimin-z#1]
Hi Jimmy! 

Your cover image looks really nice. 
I'm curious to know, what tools did you use to create it ? 

Greetings from Venezuela!

**Comment by zhimin-z** [comment]
> Hi Jimmy!
> 
> Your cover image looks really nice. I'm curious to know, what tools did you use to create it ?
> 
> Greetings from Venezuela!

Hi, Venezuela.

Thank you for reaching out. I took this photo using my standard camera and edited it in Photoshop. However, I believe there are simpler tools available on smartphones that can enhance the background and human figures.

Best,

Jimmy Zhao
